class CatalogCategorySeed {
  const CatalogCategorySeed({
    required this.id,
    required this.nameAr,
    required this.sortOrder,
  });

  final String id;
  final String nameAr;
  final int sortOrder;
}

class CatalogUnitSeed {
  const CatalogUnitSeed({
    required this.id,
    required this.nameAr,
    required this.sortOrder,
  });

  final String id;
  final String nameAr;
  final int sortOrder;
}

class CatalogItemSeed {
  const CatalogItemSeed({
    required this.id,
    required this.nameAr,
    required this.categoryId,
    required this.defaultUnit,
  });

  final String id;
  final String nameAr;
  final String categoryId;
  final String defaultUnit;
}

const defaultCatalogCategories = <CatalogCategorySeed>[
  CatalogCategorySeed(id: 'cat_01', nameAr: 'الخضار والفواكه', sortOrder: 10),
  CatalogCategorySeed(id: 'cat_02', nameAr: 'اللحوم والدواجن', sortOrder: 20),
  CatalogCategorySeed(
    id: 'cat_03',
    nameAr: 'الأسماك والمأكولات البحرية',
    sortOrder: 30,
  ),
  CatalogCategorySeed(id: 'cat_04', nameAr: 'الألبان والأجبان', sortOrder: 40),
  CatalogCategorySeed(id: 'cat_05', nameAr: 'المخبوزات', sortOrder: 50),
  CatalogCategorySeed(
    id: 'cat_06',
    nameAr: 'الأرز والمكرونة والبقوليات',
    sortOrder: 60,
  ),
  CatalogCategorySeed(id: 'cat_07', nameAr: 'المعلبات', sortOrder: 70),
  CatalogCategorySeed(id: 'cat_08', nameAr: 'البهارات والصلصات', sortOrder: 80),
  CatalogCategorySeed(id: 'cat_09', nameAr: 'الزيوت والسمن', sortOrder: 90),
  CatalogCategorySeed(id: 'cat_10', nameAr: 'المجمدات', sortOrder: 100),
  CatalogCategorySeed(id: 'cat_11', nameAr: 'الإفطار', sortOrder: 110),
  CatalogCategorySeed(id: 'cat_12', nameAr: 'المشروبات', sortOrder: 120),
  CatalogCategorySeed(
    id: 'cat_13',
    nameAr: 'الحلويات والسناكات',
    sortOrder: 130,
  ),
  CatalogCategorySeed(id: 'cat_14', nameAr: 'التنظيف والغسيل', sortOrder: 140),
  CatalogCategorySeed(id: 'cat_15', nameAr: 'الورقيات', sortOrder: 150),
  CatalogCategorySeed(id: 'cat_16', nameAr: 'العناية الشخصية', sortOrder: 160),
  CatalogCategorySeed(id: 'cat_17', nameAr: 'أدوات المطبخ', sortOrder: 170),
  CatalogCategorySeed(
    id: 'cat_18',
    nameAr: 'المستلزمات المنزلية',
    sortOrder: 180,
  ),
  CatalogCategorySeed(
    id: 'cat_19',
    nameAr: 'الإسعافات والأدوية المنزلية',
    sortOrder: 190,
  ),
];

const defaultCatalogUnits = <CatalogUnitSeed>[
  CatalogUnitSeed(id: 'unit_01', nameAr: 'كرتون', sortOrder: 10),
  CatalogUnitSeed(id: 'unit_02', nameAr: 'كيلو', sortOrder: 20),
  CatalogUnitSeed(id: 'unit_03', nameAr: 'كيس', sortOrder: 30),
  CatalogUnitSeed(id: 'unit_04', nameAr: 'حبة', sortOrder: 40),
  CatalogUnitSeed(id: 'unit_05', nameAr: 'حزمة', sortOrder: 50),
  CatalogUnitSeed(id: 'unit_06', nameAr: 'علبة', sortOrder: 60),
  CatalogUnitSeed(id: 'unit_07', nameAr: 'قالب', sortOrder: 70),
  CatalogUnitSeed(id: 'unit_08', nameAr: 'طبق', sortOrder: 80),
  CatalogUnitSeed(id: 'unit_09', nameAr: 'قارورة', sortOrder: 90),
  CatalogUnitSeed(id: 'unit_10', nameAr: 'رول', sortOrder: 100),
  CatalogUnitSeed(id: 'unit_11', nameAr: 'طقم', sortOrder: 110),
];

const defaultCatalogItems = <CatalogItemSeed>[
  CatalogItemSeed(
    id: 'item_001',
    nameAr: 'طماط',
    categoryId: 'cat_01',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_002',
    nameAr: 'خيار',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_003',
    nameAr: 'بطاط',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_004',
    nameAr: 'بصل أحمر',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_005',
    nameAr: 'بصل أبيض',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_006',
    nameAr: 'ثوم',
    categoryId: 'cat_01',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_007',
    nameAr: 'جزر',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_008',
    nameAr: 'ليمون',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_009',
    nameAr: 'فلفل بارد أخضر',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_010',
    nameAr: 'فلفل بارد أحمر',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_011',
    nameAr: 'فلفل بارد أصفر',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_012',
    nameAr: 'فلفل حار',
    categoryId: 'cat_01',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_013',
    nameAr: 'خس',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_014',
    nameAr: 'جرجير',
    categoryId: 'cat_01',
    defaultUnit: 'حزمة',
  ),
  CatalogItemSeed(
    id: 'item_015',
    nameAr: 'بقدونس',
    categoryId: 'cat_01',
    defaultUnit: 'حزمة',
  ),
  CatalogItemSeed(
    id: 'item_016',
    nameAr: 'كزبرة',
    categoryId: 'cat_01',
    defaultUnit: 'حزمة',
  ),
  CatalogItemSeed(
    id: 'item_017',
    nameAr: 'نعناع',
    categoryId: 'cat_01',
    defaultUnit: 'حزمة',
  ),
  CatalogItemSeed(
    id: 'item_018',
    nameAr: 'شبت',
    categoryId: 'cat_01',
    defaultUnit: 'حزمة',
  ),
  CatalogItemSeed(
    id: 'item_019',
    nameAr: 'ريحان',
    categoryId: 'cat_01',
    defaultUnit: 'حزمة',
  ),
  CatalogItemSeed(
    id: 'item_020',
    nameAr: 'كراث',
    categoryId: 'cat_01',
    defaultUnit: 'حزمة',
  ),
  CatalogItemSeed(
    id: 'item_021',
    nameAr: 'باذنجان',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_022',
    nameAr: 'كوسا',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_023',
    nameAr: 'قرنبيط',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_024',
    nameAr: 'بروكلي',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_025',
    nameAr: 'ملفوف أبيض',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_026',
    nameAr: 'ملفوف أحمر',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_027',
    nameAr: 'فطر طازج',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_028',
    nameAr: 'ذرة طازجة',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_029',
    nameAr: 'فاصوليا خضراء',
    categoryId: 'cat_01',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_030',
    nameAr: 'بازلاء خضراء',
    categoryId: 'cat_01',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_031',
    nameAr: 'سبانخ',
    categoryId: 'cat_01',
    defaultUnit: 'حزمة',
  ),
  CatalogItemSeed(
    id: 'item_032',
    nameAr: 'ملوخية',
    categoryId: 'cat_01',
    defaultUnit: 'حزمة',
  ),
  CatalogItemSeed(
    id: 'item_033',
    nameAr: 'ورق عنب',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_034',
    nameAr: 'زنجبيل',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_035',
    nameAr: 'شمندر',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_036',
    nameAr: 'فجل',
    categoryId: 'cat_01',
    defaultUnit: 'حزمة',
  ),
  CatalogItemSeed(
    id: 'item_037',
    nameAr: 'بطاط حلوة',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_038',
    nameAr: 'أفوكادو',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_039',
    nameAr: 'تفاح أحمر',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_040',
    nameAr: 'تفاح أخضر',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_041',
    nameAr: 'موز',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_042',
    nameAr: 'برتقال',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_043',
    nameAr: 'يوسفي',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_044',
    nameAr: 'عنب أحمر',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_045',
    nameAr: 'عنب أخضر',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_046',
    nameAr: 'فراولة',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_047',
    nameAr: 'توت أزرق',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_048',
    nameAr: 'توت أحمر',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_049',
    nameAr: 'رمان',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_050',
    nameAr: 'مانجو',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_051',
    nameAr: 'بطيخ',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_052',
    nameAr: 'شمام',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_053',
    nameAr: 'أناناس',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_054',
    nameAr: 'كيوي',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_055',
    nameAr: 'كمثرى',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_056',
    nameAr: 'خوخ',
    categoryId: 'cat_01',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_057',
    nameAr: 'مشمش',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_058',
    nameAr: 'تين',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_059',
    nameAr: 'تمر',
    categoryId: 'cat_01',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_060',
    nameAr: 'نخّي طازج',
    categoryId: 'cat_01',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_061',
    nameAr: 'جوز هند',
    categoryId: 'cat_01',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_062',
    nameAr: 'دجاج كامل',
    categoryId: 'cat_02',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_063',
    nameAr: 'دجاج مقطع',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_064',
    nameAr: 'صدور دجاج',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_065',
    nameAr: 'أفخاذ دجاج',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_066',
    nameAr: 'أجنحة دجاج',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_067',
    nameAr: 'كبدة دجاج',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_068',
    nameAr: 'لحم غنم',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_069',
    nameAr: 'لحم بقر',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_070',
    nameAr: 'لحم مفروم',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_071',
    nameAr: 'لحم مكعبات',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_072',
    nameAr: 'ريش غنم',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_073',
    nameAr: 'ستيك لحم',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_074',
    nameAr: 'كبدة غنم',
    categoryId: 'cat_02',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_075',
    nameAr: 'كباب جاهز',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_076',
    nameAr: 'كفتة جاهزة',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_077',
    nameAr: 'برجر لحم',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_078',
    nameAr: 'برجر دجاج',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_079',
    nameAr: 'نقانق',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_080',
    nameAr: 'مرتديلا',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_081',
    nameAr: 'شاورما دجاج',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_082',
    nameAr: 'شاورما لحم',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_083',
    nameAr: 'ديك رومي شرائح',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_084',
    nameAr: 'لانشون',
    categoryId: 'cat_02',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_085',
    nameAr: 'سمك زبيدي',
    categoryId: 'cat_03',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_086',
    nameAr: 'سمك هامور',
    categoryId: 'cat_03',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_087',
    nameAr: 'سمك شعري',
    categoryId: 'cat_03',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_088',
    nameAr: 'سمك نقرور',
    categoryId: 'cat_03',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_089',
    nameAr: 'سمك سبيطي',
    categoryId: 'cat_03',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_090',
    nameAr: 'سمك سالمون',
    categoryId: 'cat_03',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_091',
    nameAr: 'سمك تونة طازج',
    categoryId: 'cat_03',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_092',
    nameAr: 'فيليه سمك',
    categoryId: 'cat_03',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_093',
    nameAr: 'روبيان',
    categoryId: 'cat_03',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_094',
    nameAr: 'روبيان مقشر',
    categoryId: 'cat_03',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_095',
    nameAr: 'حبار',
    categoryId: 'cat_03',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_096',
    nameAr: 'قباقب',
    categoryId: 'cat_03',
    defaultUnit: 'كيلو',
  ),
  CatalogItemSeed(
    id: 'item_097',
    nameAr: 'محار',
    categoryId: 'cat_03',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_098',
    nameAr: 'أصابع سمك',
    categoryId: 'cat_03',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_099',
    nameAr: 'سمك مجمد',
    categoryId: 'cat_03',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_100',
    nameAr: 'حليب طازج',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_101',
    nameAr: 'حليب طويل الأمد',
    categoryId: 'cat_04',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_102',
    nameAr: 'حليب قليل الدسم',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_103',
    nameAr: 'حليب خالي الدسم',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_104',
    nameAr: 'حليب بودرة',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_105',
    nameAr: 'لبن',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_106',
    nameAr: 'روب',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_107',
    nameAr: 'زبادي',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_108',
    nameAr: 'لبنة',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_109',
    nameAr: 'قشطة',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_110',
    nameAr: 'كريمة طبخ',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_111',
    nameAr: 'كريمة خفق',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_112',
    nameAr: 'زبدة',
    categoryId: 'cat_04',
    defaultUnit: 'قالب',
  ),
  CatalogItemSeed(
    id: 'item_113',
    nameAr: 'زبدة غير مملحة',
    categoryId: 'cat_04',
    defaultUnit: 'قالب',
  ),
  CatalogItemSeed(
    id: 'item_114',
    nameAr: 'جبن شرائح',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_115',
    nameAr: 'جبن كاسات',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_116',
    nameAr: 'جبن سائل',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_117',
    nameAr: 'جبن فيتا',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_118',
    nameAr: 'جبن حلوم',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_119',
    nameAr: 'جبن موزاريلا',
    categoryId: 'cat_04',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_120',
    nameAr: 'جبن شيدر',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_121',
    nameAr: 'جبن بارميزان',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_122',
    nameAr: 'جبن قريش',
    categoryId: 'cat_04',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_123',
    nameAr: 'بيض',
    categoryId: 'cat_04',
    defaultUnit: 'طبق',
  ),
  CatalogItemSeed(
    id: 'item_124',
    nameAr: 'خبز عربي',
    categoryId: 'cat_05',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_125',
    nameAr: 'خبز إيراني',
    categoryId: 'cat_05',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_126',
    nameAr: 'توست أبيض',
    categoryId: 'cat_05',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_127',
    nameAr: 'توست أسمر',
    categoryId: 'cat_05',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_128',
    nameAr: 'صمون',
    categoryId: 'cat_05',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_129',
    nameAr: 'خبز برجر',
    categoryId: 'cat_05',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_130',
    nameAr: 'خبز هوت دوغ',
    categoryId: 'cat_05',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_131',
    nameAr: 'خبز تورتيلا',
    categoryId: 'cat_05',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_132',
    nameAr: 'خبز شباتي',
    categoryId: 'cat_05',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_133',
    nameAr: 'رقاق',
    categoryId: 'cat_05',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_134',
    nameAr: 'كرواسون',
    categoryId: 'cat_05',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_135',
    nameAr: 'دونات',
    categoryId: 'cat_05',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_136',
    nameAr: 'كيك جاهز',
    categoryId: 'cat_05',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_137',
    nameAr: 'معجنات مشكلة',
    categoryId: 'cat_05',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_138',
    nameAr: 'فطاير جبن',
    categoryId: 'cat_05',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_139',
    nameAr: 'فطاير زعتر',
    categoryId: 'cat_05',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_140',
    nameAr: 'عيش/أرز بسمتي',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_141',
    nameAr: 'أرز مصري',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_142',
    nameAr: 'أرز عنبر',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_143',
    nameAr: 'أرز قصير الحبة',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_144',
    nameAr: 'مكرونة سباغيتي',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_145',
    nameAr: 'مكرونة أقلام',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_146',
    nameAr: 'مكرونة حلزونية',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_147',
    nameAr: 'لازانيا',
    categoryId: 'cat_06',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_148',
    nameAr: 'شعيرية',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_149',
    nameAr: 'نودلز',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_150',
    nameAr: 'عدس أحمر',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_151',
    nameAr: 'عدس أسود',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_152',
    nameAr: 'حمص',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_153',
    nameAr: 'فول ناشف',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_154',
    nameAr: 'فاصوليا بيضاء',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_155',
    nameAr: 'فاصوليا حمراء',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_156',
    nameAr: 'لوبيا',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_157',
    nameAr: 'ماش',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_158',
    nameAr: 'برغل',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_159',
    nameAr: 'جريش',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_160',
    nameAr: 'هريس',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_161',
    nameAr: 'شوفان',
    categoryId: 'cat_06',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_162',
    nameAr: 'طحين أبيض',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_163',
    nameAr: 'طحين أسمر',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_164',
    nameAr: 'طحين ذرة',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_165',
    nameAr: 'نشا',
    categoryId: 'cat_06',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_166',
    nameAr: 'سميد',
    categoryId: 'cat_06',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_167',
    nameAr: 'بيكنج بودر',
    categoryId: 'cat_06',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_168',
    nameAr: 'خميرة',
    categoryId: 'cat_06',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_169',
    nameAr: 'تونة',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_170',
    nameAr: 'سردين',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_171',
    nameAr: 'فول مدمس',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_172',
    nameAr: 'حمص معلب',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_173',
    nameAr: 'فاصوليا معلبة',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_174',
    nameAr: 'ذرة معلبة',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_175',
    nameAr: 'بازلاء معلبة',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_176',
    nameAr: 'فطر معلب',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_177',
    nameAr: 'طماط مقطع',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_178',
    nameAr: 'معجون طماط',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_179',
    nameAr: 'صلصة بيتزا',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_180',
    nameAr: 'زيتون أخضر',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_181',
    nameAr: 'زيتون أسود',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_182',
    nameAr: 'مخلل خيار',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_183',
    nameAr: 'مخلل مشكل',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_184',
    nameAr: 'هالبينو',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_185',
    nameAr: 'أناناس معلب',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_186',
    nameAr: 'خوخ معلب',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_187',
    nameAr: 'حليب مبخر',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_188',
    nameAr: 'حليب مكثف',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_189',
    nameAr: 'قشطة معلبة',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_190',
    nameAr: 'شوربة معلبة',
    categoryId: 'cat_07',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_191',
    nameAr: 'ملح',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_192',
    nameAr: 'سكر أبيض',
    categoryId: 'cat_08',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_193',
    nameAr: 'سكر بني',
    categoryId: 'cat_08',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_194',
    nameAr: 'فلفل أسود',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_195',
    nameAr: 'فلفل أبيض',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_196',
    nameAr: 'كمون',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_197',
    nameAr: 'كركم',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_198',
    nameAr: 'كزبرة ناشفة',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_199',
    nameAr: 'قرفة/دارسين',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_200',
    nameAr: 'هيل',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_201',
    nameAr: 'زعفران',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_202',
    nameAr: 'قرنفل',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_203',
    nameAr: 'ورق غار',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_204',
    nameAr: 'لومي أسود',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_205',
    nameAr: 'سماق',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_206',
    nameAr: 'زعتر',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_207',
    nameAr: 'كاري',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_208',
    nameAr: 'بابريكا',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_209',
    nameAr: 'شطة بودرة',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_210',
    nameAr: 'بهارات مشكلة',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_211',
    nameAr: 'بهارات كبسة',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_212',
    nameAr: 'بهارات برياني',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_213',
    nameAr: 'بهارات دجاج',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_214',
    nameAr: 'بهارات لحم',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_215',
    nameAr: 'ثوم بودرة',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_216',
    nameAr: 'بصل بودرة',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_217',
    nameAr: 'كاتشب',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_218',
    nameAr: 'مايونيز',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_219',
    nameAr: 'خردل',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_220',
    nameAr: 'صلصة حارة',
    categoryId: 'cat_08',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_221',
    nameAr: 'صلصة باربكيو',
    categoryId: 'cat_08',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_222',
    nameAr: 'صويا صوص',
    categoryId: 'cat_08',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_223',
    nameAr: 'صلصة ورشستر',
    categoryId: 'cat_08',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_224',
    nameAr: 'خل أبيض',
    categoryId: 'cat_08',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_225',
    nameAr: 'خل تفاح',
    categoryId: 'cat_08',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_226',
    nameAr: 'دبس رمان',
    categoryId: 'cat_08',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_227',
    nameAr: 'طحينة',
    categoryId: 'cat_08',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_228',
    nameAr: 'زيت طبخ',
    categoryId: 'cat_09',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_229',
    nameAr: 'زيت ذرة',
    categoryId: 'cat_09',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_230',
    nameAr: 'زيت دوار الشمس',
    categoryId: 'cat_09',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_231',
    nameAr: 'زيت زيتون',
    categoryId: 'cat_09',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_232',
    nameAr: 'زيت جوز الهند',
    categoryId: 'cat_09',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_233',
    nameAr: 'زيت سمسم',
    categoryId: 'cat_09',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_234',
    nameAr: 'سمن',
    categoryId: 'cat_09',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_235',
    nameAr: 'سمن نباتي',
    categoryId: 'cat_09',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_236',
    nameAr: 'بخاخ زيت',
    categoryId: 'cat_09',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_237',
    nameAr: 'بطاط مجمدة',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_238',
    nameAr: 'خضار مشكلة مجمدة',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_239',
    nameAr: 'بازلاء مجمدة',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_240',
    nameAr: 'ذرة مجمدة',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_241',
    nameAr: 'ملوخية مجمدة',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_242',
    nameAr: 'سبانخ مجمدة',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_243',
    nameAr: 'سمبوسة جبن',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_244',
    nameAr: 'سمبوسة لحم',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_245',
    nameAr: 'سمبوسة دجاج',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_246',
    nameAr: 'سبرنج رول',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_247',
    nameAr: 'فطاير مجمدة',
    categoryId: 'cat_10',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_248',
    nameAr: 'بيتزا مجمدة',
    categoryId: 'cat_10',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_249',
    nameAr: 'برجر مجمد',
    categoryId: 'cat_10',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_250',
    nameAr: 'نقانق مجمدة',
    categoryId: 'cat_10',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_251',
    nameAr: 'ناجتس دجاج',
    categoryId: 'cat_10',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_252',
    nameAr: 'ستربس دجاج',
    categoryId: 'cat_10',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_253',
    nameAr: 'أصابع موزاريلا',
    categoryId: 'cat_10',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_254',
    nameAr: 'أصابع سمك',
    categoryId: 'cat_10',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_255',
    nameAr: 'آيس كريم',
    categoryId: 'cat_10',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_256',
    nameAr: 'ثلج',
    categoryId: 'cat_10',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_257',
    nameAr: 'كورن فليكس',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_258',
    nameAr: 'حبوب إفطار بالشوكولاتة',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_259',
    nameAr: 'شوفان',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_260',
    nameAr: 'عسل',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_261',
    nameAr: 'مربى فراولة',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_262',
    nameAr: 'مربى مشمش',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_263',
    nameAr: 'مربى توت',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_264',
    nameAr: 'زبدة فول سوداني',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_265',
    nameAr: 'كريمة شوكولاتة',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_266',
    nameAr: 'طحينية',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_267',
    nameAr: 'جبن سائل',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_268',
    nameAr: 'حلاوة طحينية',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_269',
    nameAr: 'فول سوداني',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_270',
    nameAr: 'بسكويت شاي',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_271',
    nameAr: 'تمرية',
    categoryId: 'cat_11',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_272',
    nameAr: 'ماي صغير',
    categoryId: 'cat_12',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_273',
    nameAr: 'ماي كبير',
    categoryId: 'cat_12',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_274',
    nameAr: 'ماي غازي',
    categoryId: 'cat_12',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_275',
    nameAr: 'عصير برتقال',
    categoryId: 'cat_12',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_276',
    nameAr: 'عصير تفاح',
    categoryId: 'cat_12',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_277',
    nameAr: 'عصير مانجو',
    categoryId: 'cat_12',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_278',
    nameAr: 'عصير مشكل',
    categoryId: 'cat_12',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_279',
    nameAr: 'مشروب غازي',
    categoryId: 'cat_12',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_280',
    nameAr: 'لبن مشروب',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_281',
    nameAr: 'حليب شوكولاتة',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_282',
    nameAr: 'قهوة عربية',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_283',
    nameAr: 'قهوة تركية',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_284',
    nameAr: 'قهوة سريعة التحضير',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_285',
    nameAr: 'كبسولات قهوة',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_286',
    nameAr: 'شاي أحمر',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_287',
    nameAr: 'شاي أخضر',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_288',
    nameAr: 'شاي كرك',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_289',
    nameAr: 'نسكافيه',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_290',
    nameAr: 'كابتشينو',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_291',
    nameAr: 'كاكاو بودرة',
    categoryId: 'cat_12',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_292',
    nameAr: 'مشروب شعير',
    categoryId: 'cat_12',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_293',
    nameAr: 'مشروب طاقة',
    categoryId: 'cat_12',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_294',
    nameAr: 'بسكويت',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_295',
    nameAr: 'بسكويت مالح',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_296',
    nameAr: 'ويفر',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_297',
    nameAr: 'شيبس',
    categoryId: 'cat_13',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_298',
    nameAr: 'بفك',
    categoryId: 'cat_13',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_299',
    nameAr: 'فشار',
    categoryId: 'cat_13',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_300',
    nameAr: 'كعك',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_301',
    nameAr: 'كيك صغير',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_302',
    nameAr: 'شوكولاتة',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_303',
    nameAr: 'حلاوة',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_304',
    nameAr: 'مصاص',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_305',
    nameAr: 'علك',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_306',
    nameAr: 'جيلي',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_307',
    nameAr: 'كاسترد',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_308',
    nameAr: 'كريم كراميل',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_309',
    nameAr: 'بودنج',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_310',
    nameAr: 'مارشميلو',
    categoryId: 'cat_13',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_311',
    nameAr: 'مكسرات مشكلة',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_312',
    nameAr: 'لوز',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_313',
    nameAr: 'كاجو',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_314',
    nameAr: 'فستق',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_315',
    nameAr: 'فصفص',
    categoryId: 'cat_13',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_316',
    nameAr: 'زبيب',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_317',
    nameAr: 'فواكه مجففة',
    categoryId: 'cat_13',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_318',
    nameAr: 'صابون ملابس بودرة',
    categoryId: 'cat_14',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_319',
    nameAr: 'صابون ملابس سائل',
    categoryId: 'cat_14',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_320',
    nameAr: 'كبسولات غسيل',
    categoryId: 'cat_14',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_321',
    nameAr: 'منعم ملابس',
    categoryId: 'cat_14',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_322',
    nameAr: 'مزيل بقع',
    categoryId: 'cat_14',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_323',
    nameAr: 'كلور',
    categoryId: 'cat_14',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_324',
    nameAr: 'مطهر أرضيات',
    categoryId: 'cat_14',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_325',
    nameAr: 'ديتول',
    categoryId: 'cat_14',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_326',
    nameAr: 'سائل صحون',
    categoryId: 'cat_14',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_327',
    nameAr: 'ملح غسالة صحون',
    categoryId: 'cat_14',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_328',
    nameAr: 'أقراص غسالة صحون',
    categoryId: 'cat_14',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_329',
    nameAr: 'ملمع غسالة صحون',
    categoryId: 'cat_14',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_330',
    nameAr: 'إسفنجة صحون',
    categoryId: 'cat_14',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_331',
    nameAr: 'ليفة تنظيف',
    categoryId: 'cat_14',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_332',
    nameAr: 'سلك صحون',
    categoryId: 'cat_14',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_333',
    nameAr: 'منظف زجاج',
    categoryId: 'cat_14',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_334',
    nameAr: 'منظف حمام',
    categoryId: 'cat_14',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_335',
    nameAr: 'منظف مطبخ',
    categoryId: 'cat_14',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_336',
    nameAr: 'منظف فرن',
    categoryId: 'cat_14',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_337',
    nameAr: 'منظف سيراميك',
    categoryId: 'cat_14',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_338',
    nameAr: 'معطر جو',
    categoryId: 'cat_14',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_339',
    nameAr: 'معطر مفارش',
    categoryId: 'cat_14',
    defaultUnit: 'قارورة',
  ),
  CatalogItemSeed(
    id: 'item_340',
    nameAr: 'أكياس زبالة صغيرة',
    categoryId: 'cat_14',
    defaultUnit: 'رول',
  ),
  CatalogItemSeed(
    id: 'item_341',
    nameAr: 'أكياس زبالة وسط',
    categoryId: 'cat_14',
    defaultUnit: 'رول',
  ),
  CatalogItemSeed(
    id: 'item_342',
    nameAr: 'أكياس زبالة كبيرة',
    categoryId: 'cat_14',
    defaultUnit: 'رول',
  ),
  CatalogItemSeed(
    id: 'item_343',
    nameAr: 'قفازات تنظيف',
    categoryId: 'cat_14',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_344',
    nameAr: 'كلينكس',
    categoryId: 'cat_15',
    defaultUnit: 'كرتون',
  ),
  CatalogItemSeed(
    id: 'item_345',
    nameAr: 'مناديل جيب',
    categoryId: 'cat_15',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_346',
    nameAr: 'مناديل مطبخ',
    categoryId: 'cat_15',
    defaultUnit: 'رول',
  ),
  CatalogItemSeed(
    id: 'item_347',
    nameAr: 'ورق حمام',
    categoryId: 'cat_15',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_348',
    nameAr: 'مناديل مبللة',
    categoryId: 'cat_15',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_349',
    nameAr: 'مناديل سفرة',
    categoryId: 'cat_15',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_350',
    nameAr: 'أكواب ورق',
    categoryId: 'cat_15',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_351',
    nameAr: 'أكواب بلاستيك',
    categoryId: 'cat_15',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_352',
    nameAr: 'صحون ورق',
    categoryId: 'cat_15',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_353',
    nameAr: 'صحون بلاستيك',
    categoryId: 'cat_15',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_354',
    nameAr: 'ملاعق بلاستيك',
    categoryId: 'cat_15',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_355',
    nameAr: 'شوك بلاستيك',
    categoryId: 'cat_15',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_356',
    nameAr: 'سكاكين بلاستيك',
    categoryId: 'cat_15',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_357',
    nameAr: 'مصاصات',
    categoryId: 'cat_15',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_358',
    nameAr: 'سفر طعام',
    categoryId: 'cat_15',
    defaultUnit: 'رول',
  ),
  CatalogItemSeed(
    id: 'item_359',
    nameAr: 'شامبو',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_360',
    nameAr: 'بلسم',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_361',
    nameAr: 'صابون جسم',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_362',
    nameAr: 'شاور جل',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_363',
    nameAr: 'غسول يد',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_364',
    nameAr: 'معقم يدين',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_365',
    nameAr: 'معجون أسنان',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_366',
    nameAr: 'فرشاة أسنان',
    categoryId: 'cat_16',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_367',
    nameAr: 'خيط أسنان',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_368',
    nameAr: 'غسول فم',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_369',
    nameAr: 'مزيل عرق',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_370',
    nameAr: 'عطر جسم',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_371',
    nameAr: 'كريم ترطيب',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_372',
    nameAr: 'لوشن جسم',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_373',
    nameAr: 'فازلين',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_374',
    nameAr: 'واقي شمس',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_375',
    nameAr: 'فوط صحية',
    categoryId: 'cat_16',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_376',
    nameAr: 'قطن أذن',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_377',
    nameAr: 'قطن طبي',
    categoryId: 'cat_16',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_378',
    nameAr: 'شفرة حلاقة',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_379',
    nameAr: 'جل حلاقة',
    categoryId: 'cat_16',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_380',
    nameAr: 'مقص أظافر',
    categoryId: 'cat_16',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_381',
    nameAr: 'مشط',
    categoryId: 'cat_16',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_382',
    nameAr: 'فرشاة شعر',
    categoryId: 'cat_16',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_383',
    nameAr: 'قصدير',
    categoryId: 'cat_17',
    defaultUnit: 'رول',
  ),
  CatalogItemSeed(
    id: 'item_384',
    nameAr: 'نايلون تغليف',
    categoryId: 'cat_17',
    defaultUnit: 'رول',
  ),
  CatalogItemSeed(
    id: 'item_385',
    nameAr: 'ورق زبدة',
    categoryId: 'cat_17',
    defaultUnit: 'رول',
  ),
  CatalogItemSeed(
    id: 'item_386',
    nameAr: 'أكياس حفظ الطعام',
    categoryId: 'cat_17',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_387',
    nameAr: 'أكياس فريزر',
    categoryId: 'cat_17',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_388',
    nameAr: 'علب حفظ طعام',
    categoryId: 'cat_17',
    defaultUnit: 'طقم',
  ),
  CatalogItemSeed(
    id: 'item_389',
    nameAr: 'قفازات مطبخ',
    categoryId: 'cat_17',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_390',
    nameAr: 'مناشف مطبخ',
    categoryId: 'cat_17',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_391',
    nameAr: 'مريلة مطبخ',
    categoryId: 'cat_17',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_392',
    nameAr: 'مصفاة',
    categoryId: 'cat_17',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_393',
    nameAr: 'فتاحة علب',
    categoryId: 'cat_17',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_394',
    nameAr: 'ملاعق خشب',
    categoryId: 'cat_17',
    defaultUnit: 'طقم',
  ),
  CatalogItemSeed(
    id: 'item_395',
    nameAr: 'مغرفة',
    categoryId: 'cat_17',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_396',
    nameAr: 'قطاعة خضار',
    categoryId: 'cat_17',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_397',
    nameAr: 'سكاكين مطبخ',
    categoryId: 'cat_17',
    defaultUnit: 'طقم',
  ),
  CatalogItemSeed(
    id: 'item_398',
    nameAr: 'لوح تقطيع',
    categoryId: 'cat_17',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_399',
    nameAr: 'صينية فرن',
    categoryId: 'cat_17',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_400',
    nameAr: 'أعواد خشب',
    categoryId: 'cat_17',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_401',
    nameAr: 'أعواد أسنان',
    categoryId: 'cat_17',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_402',
    nameAr: 'كبريت',
    categoryId: 'cat_17',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_403',
    nameAr: 'ولاعة',
    categoryId: 'cat_17',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_404',
    nameAr: 'فحم',
    categoryId: 'cat_17',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_405',
    nameAr: 'بطاريات صغيرة',
    categoryId: 'cat_18',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_406',
    nameAr: 'بطاريات وسط',
    categoryId: 'cat_18',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_407',
    nameAr: 'بطاريات كبيرة',
    categoryId: 'cat_18',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_408',
    nameAr: 'لمبات',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_409',
    nameAr: 'وصلة كهرباء',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_410',
    nameAr: 'شاحن',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_411',
    nameAr: 'سلك شاحن',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_412',
    nameAr: 'لاصق شفاف',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_413',
    nameAr: 'لاصق قوي',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_414',
    nameAr: 'صمغ',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_415',
    nameAr: 'أقلام',
    categoryId: 'cat_18',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_416',
    nameAr: 'دفتر ملاحظات',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_417',
    nameAr: 'مشابك غسيل',
    categoryId: 'cat_18',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_418',
    nameAr: 'حبل غسيل',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_419',
    nameAr: 'علاقات ملابس',
    categoryId: 'cat_18',
    defaultUnit: 'طقم',
  ),
  CatalogItemSeed(
    id: 'item_420',
    nameAr: 'معطر سيارة',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_421',
    nameAr: 'مناديل سيارة',
    categoryId: 'cat_18',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_422',
    nameAr: 'فرشة أرضية',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_423',
    nameAr: 'ممسحة أرضية',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_424',
    nameAr: 'مكنسة يدوية',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_425',
    nameAr: 'سطل',
    categoryId: 'cat_18',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_426',
    nameAr: 'بلاستر جروح',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_427',
    nameAr: 'مطهر جروح',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_428',
    nameAr: 'كحول طبي',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_429',
    nameAr: 'قطن طبي',
    categoryId: 'cat_19',
    defaultUnit: 'كيس',
  ),
  CatalogItemSeed(
    id: 'item_430',
    nameAr: 'شاش طبي',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_431',
    nameAr: 'رباط ضاغط',
    categoryId: 'cat_19',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_432',
    nameAr: 'لاصق طبي',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_433',
    nameAr: 'قفازات طبية',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_434',
    nameAr: 'كمادات حرارة',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_435',
    nameAr: 'كمادات باردة',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_436',
    nameAr: 'ميزان حرارة',
    categoryId: 'cat_19',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_437',
    nameAr: 'جهاز قياس ضغط',
    categoryId: 'cat_19',
    defaultUnit: 'حبة',
  ),
  CatalogItemSeed(
    id: 'item_438',
    nameAr: 'مسكن ألم',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_439',
    nameAr: 'خافض حرارة',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_440',
    nameAr: 'حبوب حساسية',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_441',
    nameAr: 'بخاخ أنف',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_442',
    nameAr: 'محلول ملحي',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_443',
    nameAr: 'قطرة عين',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_444',
    nameAr: 'كريم حروق',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_445',
    nameAr: 'كريم جروح',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_446',
    nameAr: 'مرهم عضلات',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_447',
    nameAr: 'فيتامينات',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_448',
    nameAr: 'معقم طبي',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
  CatalogItemSeed(
    id: 'item_449',
    nameAr: 'كمامات',
    categoryId: 'cat_19',
    defaultUnit: 'علبة',
  ),
];
